### ISSUE TITLE
Definicion de encabezado de expediente

### ISSUE THREAD

**Issue by acalcagno** [acalcagno/ExpedientesConcurso#12]
Si para un perfil se parte la informacion enviada en varios expedientes:
-La numeracion de las fojas/folios empieza de cero para cada expediente???
-El encabezado del expediente, todas esas hojas que van antes de la documentacion de los concursantes, se repite igual para cada expediente del mismo perfil??
-Los documentos del encabezado, van detallados en el indice??

**Comment by jlurgo** [comment]
-Si, la numeracion empieza de cero para cada expediente
-Si, el encabezado es igual para cada expediente del mismo perfil
-Si, van detallados.
